import { Theme } from './types';

export const themes: Theme[] = [
  {
    id: 'comida',
    name: 'Comida e Bebida',
    icon: '🍕',
    pairs: {
      easy: [
        ['Pizza', 'Bolo'],
        ['Hambúrguer', 'Sorvete'],
        ['Café', 'Cerveja'],
        ['Salada', 'Chocolate'],
        ['Churrasco', 'Suco'],
        ['Sushi', 'Pipoca'],
        ['Pão de queijo', 'Macarrão'],
        ['Feijoada', 'Pudim'],
        ['Sopa', 'Batata frita'],
        ['Refrigerante', 'Peixe'],
        ['Tapioca', 'Biscoito'],
        ['Cachorro quente', 'Torta'],
        ['Misto quente', 'Açaí'],
        ['Pastel', 'Mingau'],
        ['Estrogonofe', 'Vinho'],
        ['Arroz', 'Miojo'],
        ['Picanha', 'Maçã'],
        ['Lasanha', 'Ovo frito'],
        ['Croissant', 'Panqueca'],
        ['Água', 'Café']
      ],
      medium: [
        ['Pizza', 'Hambúrguer'],
        ['Bolo', 'Sorvete'],
        ['Café', 'Refrigerante'],
        ['Cerveja', 'Vinho'],
        ['Sushi', 'Temaki'],
        ['Pão de queijo', 'Coxinha'],
        ['Macarrão', 'Lasanha'],
        ['Feijoada', 'Churrasco'],
        ['Chocolate', 'Brigadeiro'],
        ['Suco', 'Água com gás'],
        ['Biscoito', 'Bolacha'],
        ['Pudim', 'Mousse'],
        ['Sopa', 'Caldo'],
        ['Torta doce', 'Bolo recheado'],
        ['Açaí', 'Cupuaçu'],
        ['Pastel', 'Empada'],
        ['Tapioca', 'Crepe'],
        ['Ketchup', 'Mostarda'],
        ['Arroz branco', 'Arroz integral'],
        ['Manteiga', 'Margarina']
      ],
      hard: [
        ['Pizza', 'Esfiha'],
        ['Hambúrguer', 'Sanduíche natural'],
        ['Bolo', 'Torta doce'],
        ['Café expresso', 'Café coado'],
        ['Cerveja', 'Chopp'],
        ['Coxinha', 'Pastel'],
        ['Sorvete', 'Picolé'],
        ['Brigadeiro', 'Trufa'],
        ['Macarrão', 'Nhoque'],
        ['Suco de laranja', 'Suco de limão'],
        ['Feijão preto', 'Feijão carioca'],
        ['Churrasco', 'Carne assada'],
        ['Sashimi', 'Temaki'],
        ['Refrigerante cola', 'Refrigerante guaraná'],
        ['Água tônica', 'Água com gás'],
        ['Pão francês', 'Pão de forma'],
        ['Maionese', 'Creme de leite'],
        ['Leite integral', 'Leite desnatado'],
        ['Biscoito recheado', 'Wafer'],
        ['Queijo prato', 'Mussarela']
      ]
    }
  },
  {
    id: 'lugares',
    name: 'Lugares',
    icon: '📍',
    pairs: {
      easy: [
        ['Praia', 'Shopping'],
        ['Cinema', 'Hospital'],
        ['Escola', 'Balada'],
        ['Parque', 'Aeroporto'],
        ['Academia', 'Igreja'],
        ['Restaurante', 'Estádio'],
        ['Museu', 'Supermercado'],
        ['Hotel', 'Fazenda'],
        ['Zoológico', 'Cemitério'],
        ['Teatro', 'Clínica'],
        ['Mercado', 'Praça'],
        ['Delegacia', 'Circo'],
        ['Piscina', 'Biblioteca'],
        ['Padaria', 'Banco'],
        ['Clube', 'Mecânica'],
        ['Metrô', 'Salão de beleza'],
        ['Sorveteria', 'Tribunal'],
        ['Farmácia', 'Motel'],
        ['Bar', 'Livraria'],
        ['Laboratório', 'Posto de gasolina']
      ],
      medium: [
        ['Praia', 'Piscina'],
        ['Cinema', 'Teatro'],
        ['Escola', 'Faculdade'],
        ['Shopping', 'Centro comercial'],
        ['Hospital', 'Clínica médica'],
        ['Restaurante', 'Bar'],
        ['Aeroporto', 'Rodoviária'],
        ['Parque', 'Zoológico'],
        ['Academia', 'Clube'],
        ['Supermercado', 'Padaria'],
        ['Museu', 'Galeria de arte'],
        ['Estádio', 'Ginásio'],
        ['Fazenda', 'Sítio'],
        ['Igreja', 'Templo'],
        ['Balada', 'Pub'],
        ['Biblioteca', 'Livraria'],
        ['Farmácia', 'Drogaria'],
        ['Motel', 'Hotel'],
        ['Sorveteria', 'Açaiteria'],
        ['Delegacia', 'Quartel']
      ],
      hard: [
        ['Praia', 'Clube de campo'],
        ['Cinema', 'Sala de projeção'],
        ['Restaurante', 'Bistrô'],
        ['Bar', 'Boteco'],
        ['Shopping', 'Galeria'],
        ['Aeroporto', 'Base aérea'],
        ['Hospital', 'Pronto-socorro'],
        ['Zoológico', 'Safári'],
        ['Padaria', 'Confeitaria'],
        ['Estádio', 'Arena'],
        ['Faculdade', 'Universidade'],
        ['Igreja', 'Catedral'],
        ['Supermercado', 'Atacadão'],
        ['Cemitério', 'Necrópole'],
        ['Parque de diversões', 'Parque aquático'],
        ['Biblioteca', 'Arquivo público'],
        ['Farmácia', 'Aposticário'],
        ['Rodoviária', 'Estação de trem'],
        ['Piscina', 'Lago'],
        ['Academia', 'Crossfit']
      ]
    }
  },
  {
    id: 'entretenimento',
    name: 'Entretenimento',
    icon: '🎬',
    pairs: {
      easy: [
        ['Filme', 'Videogame'],
        ['Show de música', 'Podcast'],
        ['Livro', 'Série de TV'],
        ['Teatro', 'YouTube'],
        ['Futebol', 'Novela'],
        ['Circo', 'Revista'],
        ['Balada', 'Exposição de arte'],
        ['Parque de diversões', 'Rádio'],
        ['Mágica', 'Stand-up comedy'],
        ['Documentário', 'Carnaval'],
        ['Anime', 'Novela'],
        ['Desenho animado', 'Reality show'],
        ['Jogos de tabuleiro', 'Twitch'],
        ['TikTok', 'Jornal'],
        ['Festa', 'Leitura'],
        ['K-pop', 'Música Clássica'],
        ['RPG', 'Fofoca'],
        ['História em quadrinhos', 'Novela das 8'],
        ['Boliche', 'Kart'],
        ['Pintura', 'Dança']
      ],
      medium: [
        ['Filme', 'Série de TV'],
        ['Videogame', 'Jogo de tabuleiro'],
        ['Show de música', 'Balada'],
        ['Podcast', 'Rádio'],
        ['Teatro', 'Stand-up comedy'],
        ['Livro', 'Revista'],
        ['Futebol', 'Basquete'],
        ['Parque de diversões', 'Circo'],
        ['Documentário', 'Noticiário'],
        ['Anime', 'Desenho animado'],
        ['YouTube', 'Twitch'],
        ['Novela', 'Série dramática'],
        ['TikTok', 'Instagram Reels'],
        ['Mágica', 'Ilusionismo'],
        ['Carnaval', 'Festa a fantasia'],
        ['Reality show', 'Game show'],
        ['História em quadrinhos', 'Mangá'],
        ['Boliche', 'Sinuca'],
        ['Dança', 'Balé'],
        ['Música pop', 'Música eletrônica']
      ],
      hard: [
        ['Série de TV', 'Minissérie'],
        ['Videogame', 'Jogo de PC'],
        ['Podcast', 'Audiobook'],
        ['Teatro', 'Musical'],
        ['Livro', 'E-book'],
        ['Documentário', 'Reportagem especial'],
        ['Anime', 'Animação 3D'],
        ['Futebol', 'Futsal'],
        ['YouTube', 'Vimeo'],
        ['Novela', 'Dorama'],
        ['Jogo de tabuleiro', 'Card game'],
        ['Stand-up comedy', 'Improviso'],
        ['Revista', 'Gibi'],
        ['Carnaval', 'Micareta'],
        ['Reality show', 'Talent show'],
        ['Instagram', 'Snapchat'],
        ['Música ao vivo', 'Playback'],
        ['Boliche', 'Bocha'],
        ['Dança de salão', 'Tango'],
        ['RPG de mesa', 'RPG de ação']
      ]
    }
  },
  {
    id: 'jogos',
    name: 'Personagens de Jogos',
    icon: '🎮',
    pairs: {
      easy: [
        ['Mario', 'Kratos'],
        ['Sonic', 'Pikachu'],
        ['Pac-Man', 'Master Chief'],
        ['Lara Croft', 'Steve (Minecraft)'],
        ['Zelda', 'Ryu (Street Fighter)'],
        ['Donkey Kong', 'Geralt de Rivia'],
        ['Luigi', 'Crash Bandicoot'],
        ['Kirby', 'Sub-Zero'],
        ['Bowser', 'Ezio (Assassin\'s Creed)'],
        ['Mega Man', 'Arthur Morgan']
      ],
      medium: [
        ['Mario', 'Luigi'],
        ['Kratos', 'Geralt de Rivia'],
        ['Sonic', 'Crash Bandicoot'],
        ['Ryu', 'Ken'],
        ['Pikachu', 'Charizard'],
        ['Sub-Zero', 'Scorpion'],
        ['Lara Croft', 'Nathan Drake'],
        ['Master Chief', 'Doomguy'],
        ['Zelda', 'Link'],
        ['Leon Kennedy', 'Chris Redfield']
      ],
      hard: [
        ['Mario', 'Wario'],
        ['Luigi', 'Waluigi'],
        ['Ryu', 'Akuma'],
        ['Kratos', 'Atreus'],
        ['Sonic', 'Shadow'],
        ['Pikachu', 'Pichu'],
        ['Scorpion', 'Noob Saibot'],
        ['Link', 'Dark Link'],
        ['Leon Kennedy', 'Ada Wong'],
        ['Geralt de Rivia', 'Ciri']
      ]
    }
  },
  {
    id: 'cantores',
    name: 'Música & Cantores',
    icon: '🎤',
    pairs: {
      easy: [
        ['Michael Jackson', 'Anitta'],
        ['Elvis Presley', 'Roberto Carlos'],
        ['Beyoncé', 'Gusttavo Lima'],
        ['Freddie Mercury', 'Luan Santana'],
        ['Madonna', 'Zeca Pagodinho'],
        ['Justin Bieber', 'Wesley Safadão'],
        ['Taylor Swift', 'Ivete Sangalo'],
        ['Ed Sheeran', 'Marília Mendonça'],
        ['Adele', 'Pabllo Vittar'],
        ['Eminem', 'Raça Negra']
      ],
      medium: [
        ['Michael Jackson', 'Bruno Mars'],
        ['Anitta', 'Ludmilla'],
        ['Gusttavo Lima', 'Luan Santana'],
        ['Beyoncé', 'Rihanna'],
        ['Elvis Presley', 'Frank Sinatra'],
        ['Marília Mendonça', 'Maiara e Maraisa'],
        ['Taylor Swift', 'Katy Perry'],
        ['Zeca Pagodinho', 'Thiaguinho'],
        ['Eminem', '50 Cent'],
        ['Justin Bieber', 'Shawn Mendes']
      ],
      hard: [
        ['Michael Jackson', 'The Weeknd'],
        ['Anitta', 'Luísa Sonza'],
        ['Gusttavo Lima', 'Jorge e Mateus'],
        ['Beyoncé', 'Alicia Keys'],
        ['Elvis Presley', 'Johnny Cash'],
        ['Marília Mendonça', 'Naiara Azevedo'],
        ['Taylor Swift', 'Selena Gomez'],
        ['Zeca Pagodinho', 'Arlindo Cruz'],
        ['Eminem', 'Dr. Dre'],
        ['Justin Bieber', 'Zayn Malik']
      ]
    }
  },
  {
    id: 'animes',
    name: 'Personagens de Anime',
    icon: '🎌',
    pairs: {
      easy: [
        ['Goku', 'Naruto'],
        ['Luffy', 'Pikachu'],
        ['Saitama', 'Levi Ackerman'],
        ['Ash Ketchum', 'Light Yagami'],
        ['Vegeta', 'Eren Yeager'],
        ['Zoro', 'Sasuke'],
        ['Gojo Satoru', 'Inuyasha'],
        ['Tanjiro', 'Seiya de Pégaso'],
        ['Edward Elric', 'Ichigo'],
        ['Deku', 'Yugi Muto']
      ],
      medium: [
        ['Goku', 'Vegeta'],
        ['Naruto', 'Sasuke'],
        ['Luffy', 'Zoro'],
        ['Eren Yeager', 'Levi Ackerman'],
        ['Ash Ketchum', 'Goh'],
        ['Tanjiro', 'Zenitsu'],
        ['Gojo Satoru', 'Megumi Fushiguro'],
        ['Deku', 'Bakugo'],
        ['Light Yagami', 'L'],
        ['Edward Elric', 'Alphonse Elric']
      ],
      hard: [
        ['Goku', 'Gohan'],
        ['Naruto', 'Boruto'],
        ['Luffy', 'Ace'],
        ['Eren Yeager', 'Zeke Yeager'],
        ['Vegeta', 'Trunks'],
        ['Sasuke', 'Itachi'],
        ['Gojo Satoru', 'Sukuna'],
        ['Deku', 'All Might'],
        ['Tanjiro', 'Nezuko'],
        ['Edward Elric', 'Roy Mustang']
      ]
    }
  },
  {
    id: 'dia-a-dia',
    name: 'Dia a Dia',
    icon: '👕',
    pairs: {
      easy: [
        ['Escova de dentes', 'Sabonete'],
        ['Cama', 'Geladeira'],
        ['Sofá', 'Televisão'],
        ['Mesa', 'Cadeira'],
        ['Vassoura', 'Balde'],
        ['Prato', 'Copo'],
        ['Garfo', 'Faca'],
        ['Travesseiro', 'Cobertor'],
        ['Toalha', 'Shampoo'],
        ['Roupas', 'Sapatos'],
        ['Fogão', 'Micro-ondas'],
        ['Ventilador', 'Ar-condicionado'],
        ['Chave', 'Carteira'],
        ['Celular', 'Carregador'],
        ['Mochila', 'Caderno'],
        ['Relógio', 'Óculos'],
        ['Guarda-chuva', 'Capa de chuva'],
        ['Tapete', 'Cortina'],
        ['Janela', 'Porta'],
        ['Espelho', 'Pente']
      ],
      medium: [
        ['Escova de dentes', 'Fio dental'],
        ['Cama', 'Colchão'],
        ['Sofá', 'Poltrona'],
        ['Mesa', 'Bancada'],
        ['Vassoura', 'Rodo'],
        ['Prato', 'Tigela'],
        ['Garfo', 'Colher'],
        ['Travesseiro', 'Almofada'],
        ['Toalha', 'Roupão'],
        ['Roupas', 'Camiseta'],
        ['Fogão', 'Forno'],
        ['Ventilador', 'Umidificador'],
        ['Chave', 'Cadeado'],
        ['Celular', 'Tablet'],
        ['Mochila', 'Bolsa'],
        ['Relógio', 'Pulseira'],
        ['Geladeira', 'Freezer'],
        ['Tapete', 'Capacho'],
        ['Televisão', 'Monitor'],
        ['Espelho', 'Vidro']
      ],
      hard: [
        ['Escova de dentes', 'Escova elétrica'],
        ['Cama de solteiro', 'Cama de casal'],
        ['Sofá-cama', 'Sofá retrátil'],
        ['Mesa de jantar', 'Mesa de centro'],
        ['Vassoura', 'Aspirador de pó'],
        ['Prato raso', 'Prato fundo'],
        ['Garfo', 'Hashi'],
        ['Travesseiro', 'Travesseiro ortopédico'],
        ['Toalha de banho', 'Toalha de rosto'],
        ['Camiseta', 'Camisa social'],
        ['Fogão', 'Cooktop'],
        ['Ventilador de teto', 'Ventilador de mesa'],
        ['Chave tetra', 'Chave comum'],
        ['Celular', 'Telefone fixo'],
        ['Mochila', 'Maleta'],
        ['Relógio de pulso', 'Relógio de parede'],
        ['Geladeira frost free', 'Geladeira comum'],
        ['Tapete', 'Carpete'],
        ['Cortina', 'Persiana'],
        ['Espelho de parede', 'Espelho de mão']
      ]
    }
  }
];

export function getThemeById(id: string): Theme | undefined {
  return themes.find(t => t.id === id);
}

// Add groupCount for UI
themes.forEach(t => {
  t.groupCount = t.pairs.easy.length + t.pairs.medium.length + t.pairs.hard.length;
});
